#!/bin/bash
TMP_C=/tmp/ce.$$.c
TMP_O=/tmp/ce.$$.out
:> $TMP_C

ADD_MAIN=0
VERBOSE=0
TRACE=
while getopts I:i:mvLSh OPT; do
	case $OPT in
	"I")	echo '#include <'$OPTARG'>' >> $TMP_C;;
	"i")	echo '#include "'$OPTARG'"' >> $TMP_C;;
	"m")	ADD_MAIN=1;;
	"v")	VERBOSE=1;;
	"L")	TRACE=ltrace;;
	"S")	TRACE=strace;;
	"h")	echo "usage: ce [-I header] [-i user_header] [-hmvLS] ['C source']";
			echo "Execute given C source like 1-liner."
			echo '    -h :        show this help'
			echo '    -m :        put code into main function'
			echo '    -v :        show compiled code'
			echo '    -I header : include <header>'
			echo '    -i header : include "header"'
			echo '    -L        : trace with ltrace'
			echo '    -S        : trace with strace'
			rm -f $TMP_C
			exit;;
	esac
done
shift `expr $OPTIND - 1`

[ $ADD_MAIN = 1 ] && echo 'int main(int argc, char**argv) {' >> $TMP_C
if [ "$1" != "" ]; then
	echo "$1" >> $TMP_C
else
	echo reading source from stdin ...
	cat >> $TMP_C
fi
[ $ADD_MAIN = 1 ] && echo '; return 0; }' >> $TMP_C
[ $VERBOSE = 1 ] && cat $TMP_C
shift 1;
[ $VERBOSE = 1 ] && echo gcc $CFLAGS $LDFLAGS $TMP_C -o $TMP_O \&\& $TMP_O $*
gcc $CFLAGS $LDFLAGS $TMP_C -o $TMP_O && $TRACE $TMP_O $*
STATUS=$?
rm -f $TMP_O $TMP_C
exit $STATUS
