#!/bin/sh

if ! which plagger > /dev/null; then
	echo "Install plagger at first" >&2
	exit 1
fi

case "$1" in
-h|--help)
	cat <<EOS
Someone once said... "Plagger is a LL"

usage: $0 [option] [--] script-file ...
       $0 [option] < script-file

Options:
  -h --help      display this help and exit
  -v --version   display version information and exit
EOS
	exit 0 ;;

-v|--version)
	echo "run-plagger" '$Rev: 956 $' "(`plagger --version`)"
	exit 0 ;;
--)
	shift
	;;
esac

if [ -z "$@" ]; then
	plagger -c -
	exit $?
else
	for script in $@; do
		plagger -c "$script" || exit $?
	done
fi
